### ISSUE TITLE
Getting following stack when django-linter fired

### ISSUE THREAD

**Issue by tripples** [geerk/django_linter#2]
$ django-linter managerQ
Traceback (most recent call last):
  File "/usr/local/bin/django-linter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/django_linter/main.py", line 26, in main
    linter.check(args.targets)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 747, in check
    self._do_check(files_or_modules)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 869, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 946, in check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 874, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 874, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 874, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 874, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 874, in walk
    self.walk(child)
  File "/usr/local/lib/python2.7/dist-packages/pylint/utils.py", line 871, in walk
    cb(astroid)
  File "/usr/local/lib/python2.7/dist-packages/django_linter/checkers/views.py", line 71, in visit_getattr
    if parent.attrname == 'get':
AttributeError: 'Assign' object has no attribute 'attrname'

**Comment by geerk** [comment]
@tripples thanks for bugreport, I've fixed this bug in 0.6.dev2, you can try it installing directly from github:
`pip install git+https://github.com/geerk/django_linter.git`

**Comment by tripples** [comment]
Thanks. I shall check and let you know.

**Comment by tripples** [comment]
@geerk  Update module. Issue is resolved.
